### PR TITLE
Update Alpine 3.18 → 3.19

### PR DESCRIPTION
**Pull request by jandubois**
Also merge other upstream changes like

* log console boot messages for VZ mode
* install tzdata to enable syncing of time zone between host and guest
* update openresty → rd-openresty to avoid package name conflict with upstream
* remove cgroups hack for hybrid mode in Alpine 3.18

This image has been tested with https://github.com/rancher-sandbox/rancher-desktop/pull/6373 and worked fine with `kind`, `k3d`, and the buildkit/buildx specific BATS tests.

### CODE REVIEW

**Review by mook-as — CHANGES_REQUESTED** [review]
Jan says there's issues with openresty (we're not using our custom ones).

**Comment by jandubois** [comment]
> Jan says there's issues with openresty (we're not using our custom ones).

Yes: https://github.com/rancher-sandbox/rancher-desktop/issues/6333

**Comment by jandubois** [comment]
> Jan says there's issues with openresty (we're not using our custom ones).

At least all obvious issues have been resolved:

This image has been tested with https://github.com/rancher-sandbox/rancher-desktop/pull/6373 and worked fine with kind, k3d, and the buildkit/buildx specific BATS tests.

**Review by mook-as — APPROVED** [review]
Looks reasonable, and Jan has already tested various uses of the cgroups change.

(We'll need to relnote that, but that shouldn't be an issue.)

**Pull request merged**
